name: Sibylle & Michi
avatar: /static/images/avatar.png
occupation: Tiny House Bewohner
email: michi.mauch@gmail.com
linkedin: https://www.linkedin.com/in/michimauch/
instagram: https://www.instagram.com/kokomo.house
facebook: https://www.facebook.com/groups/tinyhousecommunityschweiz
